# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "zsteg"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrey \"Zed\" Zaikin"]
  s.date = "2013-01-09"
  s.email = "zed.0xff@gmail.com"
  s.executables = ["zsteg"]
  s.extra_rdoc_files = [
    "README.md",
    "README.md.tpl",
    "TODO"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "README.md.tpl",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/zsteg",
    "cmp_bmp.rb",
    "cmp_png.rb",
    "lib/zsteg.rb",
    "lib/zsteg/checker.rb",
    "lib/zsteg/checker/wbstego.rb",
    "lib/zsteg/cli.rb",
    "lib/zsteg/extractor.rb",
    "lib/zsteg/extractor/byte_extractor.rb",
    "lib/zsteg/extractor/color_extractor.rb",
    "lib/zsteg/file_cmd.rb",
    "lib/zsteg/result.rb",
    "pngsteg.gemspec",
    "samples/06_enc.png",
    "samples/Code.png",
    "samples/README",
    "samples/camouflage-password.png",
    "samples/camouflage.png",
    "samples/cats.png",
    "samples/flower.png",
    "samples/flower_rgb1.png",
    "samples/flower_rgb2.png",
    "samples/flower_rgb3.png",
    "samples/flower_rgb4.png",
    "samples/flower_rgb5.png",
    "samples/flower_rgb6.png",
    "samples/montenach-enc.png",
    "samples/ndh2k12_sp113.bmp.7z",
    "samples/openstego_q2.png",
    "samples/openstego_send.png",
    "samples/stg300.png",
    "samples/wbsteg_noenc.bmp",
    "samples/wbsteg_noenc_17.bmp",
    "samples/wbsteg_noenc_even.bmp",
    "samples/wbsteg_noenc_even_17.bmp",
    "spec/camouflage_spec.rb",
    "spec/cats_spec.rb",
    "spec/flowers_spec.rb",
    "spec/openstego_spec.rb",
    "spec/simple_spec.rb",
    "spec/spec_helper.rb",
    "spec/wbstego_spec.rb",
    "spec/zlib_spec.rb"
  ]
  s.homepage = "http://github.com/zed-0xff/zsteg"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Detect stegano-hidden data in PNG & BMP files."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<zpng>, [">= 0.2.1"])
      s.add_runtime_dependency(%q<awesome_print>, [">= 0"])
      s.add_runtime_dependency(%q<iostruct>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<zpng>, [">= 0.2.1"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
      s.add_dependency(%q<iostruct>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<zpng>, [">= 0.2.1"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
    s.add_dependency(%q<iostruct>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

